### ISSUE TITLE
I would like to have a look at the way you structure firestore collections.

### ISSUE THREAD

**Issue by HoracioLopezCarvajal** [TheAlphamerc/react-instagram#1]
Hi, amazing work here mate

is there any chance that we can check the firestore schema (structure), I would like to have a look at the way you structure firestore collections.

are you using cloud functions to propagate any data changes?

I am trying to find solutions for some scenarios for example:
where we need to update older tweets when the user changes their profile picture. I believe that this is still an active issue with Fwitter.

you might want to check this out, this project provides solid solutions to such scenarios.

**Comment by TheAlphamerc** [comment]
Hey, @HoracioLopezCarvajal  I am using simply firebase packages to operate data. There is no use of cloud firestore in it.   check the below screenshot for the scheme.

![Screenshot 2022-02-05 at 10 47 35 AM](https://user-images.githubusercontent.com/37103237/152629763-b490c9c2-d860-4f4b-b6e5-56f5b3e48b18.png)

![Screenshot 2022-02-05 at 10 47 56 AM](https://user-images.githubusercontent.com/37103237/152629794-a70652f1-5046-417e-8837-b3a780fa46b9.png)

Regarding the Fwitter issue, I think that will be only possible through cloud function.
