### ISSUE TITLE
is there any chance that we can have a look at the firestore schema (structure)

### ISSUE THREAD

**Issue by HoracioLopezCarvajal** [TheAlphamerc/react-instagram#3]
is there any chance that we can have a look at the firestore schema (structure)

**Comment by TheAlphamerc** [comment]
@HoracioLopezCarvajal if you want to ask something pls do ask but make sure not to create multiple issues for same qauery.
BTW I have added screenshot of schema here -> https://github.com/TheAlphamerc/react-instagram/issues/1#issuecomment-1030530537
